In [5]:
import os
import pandas as pd

base_path = "/kaggle/input/datasets/rishab260/uta-reallife-drowsiness-dataset"

data = []

valid_extensions = (".mov", ".mp4", ".avi", ".mkv")

for fold in os.listdir(base_path):
    fold_path = os.path.join(base_path, fold)

    if not os.path.isdir(fold_path):
        continue

    inner_path = os.path.join(fold_path, fold)

    if not os.path.isdir(inner_path):
        continue

    for subject in os.listdir(inner_path):
        subject_path = os.path.join(inner_path, subject)

        if not os.path.isdir(subject_path):
            continue

        for video in os.listdir(subject_path):

            video_clean = video.lower().strip()

            if not video_clean.endswith(valid_extensions):
                continue

            name = video_clean.split('.')[0]

            if name == "0":
                label = "Alert"
            elif name == "5":
                label = "Low Vigilance"
            elif name == "10":
                label = "Drowsy"
            else:
                print("Skipped (unknown):", video)
                continue

            data.append({
                "fold": fold,
                "subject": subject,
                "video": video,
                "label": label,
                "path": os.path.join(subject_path, video)
            })

df = pd.DataFrame(data)

print("✅ Total rows:", len(df))
display(df.head())

# ✅ 🔥 SAVE FILE (IMPORTANT)
save_path = "/kaggle/working/metadata_clean.csv"
df.to_csv(save_path, index=False)

print(f"✅ Metadata saved at: {save_path}")

Skipped (unknown): 10_1.mp4
Skipped (unknown): 10_2.mp4
✅ Total rows: 141

,fold,subject,video,label,path
0,Fold4_part2,47,5.mp4,Low Vigilance,/kaggle/input/datasets/rishab260/uta-reallife-...
1,Fold4_part2,47,10.mp4,Drowsy,/kaggle/input/datasets/rishab260/uta-reallife-...
2,Fold4_part2,47,0.mp4,Alert,/kaggle/input/datasets/rishab260/uta-reallife-...
3,Fold4_part2,45,5.mp4,Low Vigilance,/kaggle/input/datasets/rishab260/uta-reallife-...
4,Fold4_part2,45,10.mp4,Drowsy,/kaggle/input/datasets/rishab260/uta-reallife-...

✅ Metadata saved at: /kaggle/working/metadata_clean.csv

In [6]:
%pip install -q mediapipe opencv-python-headless scikit-learn tqdm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 74.9 MB/s eta 0:00:00:00:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.8/135.8 kB 6.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
Note: you may need to restart the kernel to use updated packages.

In [7]:
# If mediapipe is not installed, run this once:
# %pip install -q mediapipe opencv-python-headless scikit-learn tqdm

import os
import cv2
import numpy as np
import pandas as pd
import mediapipe as mp
from tqdm import tqdm

from mediapipe.tasks import python
from mediapipe.tasks.python import vision

print("mediapipe:", mp.__version__)
print("opencv:", cv2.__version__)

2026-05-01 05:12:30.858177: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777612351.135440      57 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777612351.208306      57 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777612351.878409      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777612351.878462      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777612351.878465      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777612351.878467      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

mediapipe: 0.10.35
opencv: 4.13.0

In [8]:
!wget -q -O face_landmarker.task https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/latest/face_landmarker.task

print("Model downloaded ✅")

Model downloaded ✅

In [9]:
base_options = python.BaseOptions(
    model_asset_path="face_landmarker.task"
)

options = vision.FaceLandmarkerOptions(
    base_options=base_options,
    running_mode=vision.RunningMode.IMAGE,
    num_faces=1,
    output_face_blendshapes=False,
    output_facial_transformation_matrixes=False
)

detector = vision.FaceLandmarker.create_from_options(options)

print("FaceLandmarker ready ✅")

FaceLandmarker ready ✅

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1777612376.952080     138 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1777612376.997356     140 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1777612377.027249     140 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

In [10]:
# Eye landmarks for EAR
LEFT_EYE = [33, 160, 158, 133, 153, 144]
RIGHT_EYE = [362, 385, 387, 263, 373, 380]

# Mouth landmarks for MAR
MOUTH_TOP = 13
MOUTH_BOTTOM = 14
MOUTH_LEFT = 78
MOUTH_RIGHT = 308

# Approximate head pose landmarks
NOSE = 1
CHIN = 152
LEFT_FACE = 234
RIGHT_FACE = 454

In [11]:
def compute_EAR(landmarks, eye):
    """
    EAR = Eye Aspect Ratio.
    Smaller EAR usually means eyes are closing.
    """
    p1, p2, p3, p4, p5, p6 = [np.array(landmarks[i][:2]) for i in eye]

    vertical1 = np.linalg.norm(p2 - p6)
    vertical2 = np.linalg.norm(p3 - p5)
    horizontal = np.linalg.norm(p1 - p4)

    return (vertical1 + vertical2) / (2.0 * horizontal + 1e-6)


def compute_MAR(landmarks):
    """
    MAR = Mouth Aspect Ratio.
    Larger MAR can indicate yawning/open mouth.
    """
    top = np.array(landmarks[MOUTH_TOP][:2])
    bottom = np.array(landmarks[MOUTH_BOTTOM][:2])
    left = np.array(landmarks[MOUTH_LEFT][:2])
    right = np.array(landmarks[MOUTH_RIGHT][:2])

    vertical = np.linalg.norm(top - bottom)
    horizontal = np.linalg.norm(left - right)

    return vertical / (horizontal + 1e-6)


def compute_head_pose_approx(landmarks):
    """
    Approximate head pose features.
    This is NOT true 3D pose, but useful as simple geometric features.
    """
    nose = np.array(landmarks[NOSE][:2])
    chin = np.array(landmarks[CHIN][:2])
    left = np.array(landmarks[LEFT_FACE][:2])
    right = np.array(landmarks[RIGHT_FACE][:2])

    pitch = np.linalg.norm(nose - chin)
    yaw = np.linalg.norm(left - right)

    return pitch, yaw

In [12]:
def get_face_landmarks_from_frame(frame_bgr):
    """
    Uses new MediaPipe Tasks API.
    Input: OpenCV BGR frame
    Output: list of pixel landmarks [(x, y, z), ...] or None
    """

    rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)

    mp_image = mp.Image(
        image_format=mp.ImageFormat.SRGB,
        data=rgb
    )

    result = detector.detect(mp_image)

    if not result.face_landmarks:
        return None

    h, w, _ = frame_bgr.shape

    landmarks_px = []
    for lm in result.face_landmarks[0]:
        x = int(lm.x * w)
        y = int(lm.y * h)
        z = lm.z
        landmarks_px.append((x, y, z))

    return landmarks_px

In [13]:
def process_video(path, label, subject, sample_rate=10):
    """
    Extracts EAR, MAR, pitch, yaw from video frames using MediaPipe Tasks API.
    """

    cap = cv2.VideoCapture(path)

    frame_id = 0
    rows = []
    failed_frames = 0
    processed_frames = 0

    if not cap.isOpened():
        print("Could not open video:", path)
        return rows

    while True:
        ret, frame = cap.read()

        if not ret:
            break

        frame_id += 1

        # Process every Nth frame
        if frame_id % sample_rate != 0:
            continue

        processed_frames += 1

        landmarks = get_face_landmarks_from_frame(frame)

        if landmarks is None:
            failed_frames += 1
            continue

        try:
            left_ear = compute_EAR(landmarks, LEFT_EYE)
            right_ear = compute_EAR(landmarks, RIGHT_EYE)
            EAR = (left_ear + right_ear) / 2.0

            MAR = compute_MAR(landmarks)
            pitch, yaw = compute_head_pose_approx(landmarks)

            rows.append({
                "subject": subject,
                "label": label,
                "frame": frame_id,
                "EAR": EAR,
                "MAR": MAR,
                "pitch": pitch,
                "yaw": yaw,
                "video_path": path
            })

        except Exception as e:
            failed_frames += 1
            # optional debug:
            # print("Feature extraction error:", e)

    cap.release()

    print(
        f"Done: {os.path.basename(path)} | "
        f"processed={processed_frames}, saved={len(rows)}, failed={failed_frames}"
    )

    return rows

In [14]:
df = pd.read_csv("/kaggle/working/metadata_clean.csv")

sample = df.iloc[0]

rows = process_video(
    sample["path"],
    sample["label"],
    sample["subject"],
    sample_rate=10
)

test_df = pd.DataFrame(rows)
print("Frames extracted:", len(test_df))
display(test_df.head())

Done: 5.mp4 | processed=1802, saved=1802, failed=0
Frames extracted: 1802

,subject,label,frame,EAR,MAR,pitch,yaw,video_path
0,47,Low Vigilance,10,0.295778,0.000000,258.414396,425.856783,/kaggle/input/datasets/rishab260/uta-reallife-...
1,47,Low Vigilance,20,0.287280,0.007511,242.596373,414.435761,/kaggle/input/datasets/rishab260/uta-reallife-...
2,47,Low Vigilance,30,0.285697,0.000000,243.392687,424.445521,/kaggle/input/datasets/rishab260/uta-reallife-...
3,47,Low Vigilance,40,0.296530,0.007654,238.581223,418.001196,/kaggle/input/datasets/rishab260/uta-reallife-...
4,47,Low Vigilance,50,0.283510,0.008033,240.520269,414.837318,/kaggle/input/datasets/rishab260/uta-reallife-...

In [15]:
import os
from tqdm import tqdm

save_dir = "/kaggle/working/features"
os.makedirs(save_dir, exist_ok=True)

for i, row in tqdm(df.iterrows(), total=len(df)):

    save_file = os.path.join(save_dir, f"features_{i}.csv")

    # ✅ skip already processed (important for resume)
    if os.path.exists(save_file):
        print(f"Skipping {i}, already done")
        continue

    try:
        rows = process_video(
            row["path"],
            row["label"],
            row["subject"],
            sample_rate=10
        )

        pd.DataFrame(rows).to_csv(save_file, index=False)

        print(f"✅ Saved: {save_file}")

    except Exception as e:
        print("❌ Error:", row["path"], e)

  1%|          | 1/141 [03:18<7:43:03, 198.45s/it]

Done: 5.mp4 | processed=1802, saved=1802, failed=0
✅ Saved: /kaggle/working/features/features_0.csv

  1%|▏         | 2/141 [06:46<7:52:26, 203.93s/it]

Done: 10.mp4 | processed=1834, saved=1834, failed=0
✅ Saved: /kaggle/working/features/features_1.csv

  2%|▏         | 3/141 [10:05<7:44:21, 201.90s/it]

Done: 0.mp4 | processed=1802, saved=1802, failed=0
✅ Saved: /kaggle/working/features/features_2.csv

  3%|▎         | 4/141 [10:29<5:00:23, 131.56s/it]

Done: 5.mp4 | processed=900, saved=900, failed=0
✅ Saved: /kaggle/working/features/features_3.csv

  4%|▎         | 5/141 [10:54<3:30:47, 93.00s/it]

Done: 10.mp4 | processed=925, saved=923, failed=2
✅ Saved: /kaggle/working/features/features_4.csv

  4%|▍         | 6/141 [11:14<2:33:39, 68.29s/it]

Done: 0.mp4 | processed=771, saved=771, failed=0
✅ Saved: /kaggle/working/features/features_5.csv

  5%|▍         | 7/141 [12:20<2:30:34, 67.42s/it]

Done: 5.mp4 | processed=1812, saved=1795, failed=17
✅ Saved: /kaggle/working/features/features_6.csv

  6%|▌         | 8/141 [15:27<3:54:26, 105.77s/it]

Done: 10.mp4 | processed=1802, saved=1794, failed=8
✅ Saved: /kaggle/working/features/features_7.csv

  6%|▋         | 9/141 [18:36<4:49:37, 131.65s/it]

Done: 0.mp4 | processed=1802, saved=1800, failed=2
✅ Saved: /kaggle/working/features/features_8.csv

  7%|▋         | 10/141 [20:30<4:35:20, 126.11s/it]

Done: 5.mp4 | processed=1819, saved=1819, failed=0
✅ Saved: /kaggle/working/features/features_9.csv

  8%|▊         | 11/141 [22:28<4:27:52, 123.64s/it]

Done: 10.mov | processed=1808, saved=1807, failed=1
✅ Saved: /kaggle/working/features/features_10.csv

  9%|▊         | 12/141 [24:32<4:26:28, 123.94s/it]

Done: 0.mov | processed=1811, saved=1810, failed=1
✅ Saved: /kaggle/working/features/features_11.csv

  9%|▉         | 13/141 [26:17<4:11:42, 117.99s/it]

Done: 10.mov | processed=1777, saved=1777, failed=0
✅ Saved: /kaggle/working/features/features_12.csv

 10%|▉         | 14/141 [26:58<3:20:43, 94.83s/it]

Done: 10.mov | processed=729, saved=729, failed=0
✅ Saved: /kaggle/working/features/features_13.csv

 11%|█         | 15/141 [27:39<2:45:13, 78.68s/it]

Done: 0.mov | processed=736, saved=736, failed=0
✅ Saved: /kaggle/working/features/features_14.csv

 11%|█▏        | 16/141 [28:21<2:20:53, 67.63s/it]

Done: 5.mov | processed=735, saved=735, failed=0
✅ Saved: /kaggle/working/features/features_15.csv

 12%|█▏        | 17/141 [31:09<3:22:04, 97.78s/it]

Done: 10.MOV | processed=1837, saved=1837, failed=0
✅ Saved: /kaggle/working/features/features_16.csv

 13%|█▎        | 18/141 [34:16<4:15:25, 124.60s/it]

Done: 0.MOV | processed=1890, saved=1889, failed=1
✅ Saved: /kaggle/working/features/features_17.csv

 13%|█▎        | 19/141 [37:19<4:48:59, 142.13s/it]

Done: 5.MOV | processed=1818, saved=1817, failed=1
✅ Saved: /kaggle/working/features/features_18.csv

 14%|█▍        | 20/141 [38:53<4:17:41, 127.78s/it]

Done: 10.MOV | processed=1862, saved=1862, failed=0
✅ Saved: /kaggle/working/features/features_19.csv

 15%|█▍        | 21/141 [40:31<3:57:33, 118.78s/it]

Done: 0.MOV | processed=1972, saved=1972, failed=0
✅ Saved: /kaggle/working/features/features_20.csv

 16%|█▌        | 22/141 [42:23<3:51:11, 116.57s/it]

Done: 5.MOV | processed=1877, saved=1875, failed=2
✅ Saved: /kaggle/working/features/features_21.csv

 16%|█▋        | 23/141 [45:47<4:40:50, 142.80s/it]

Done: 5.mp4 | processed=1801, saved=1799, failed=2
✅ Saved: /kaggle/working/features/features_22.csv

 17%|█▋        | 24/141 [49:01<5:08:34, 158.25s/it]

Done: 10.mp4 | processed=1798, saved=1796, failed=2
✅ Saved: /kaggle/working/features/features_23.csv

 18%|█▊        | 25/141 [52:32<5:36:25, 174.02s/it]

Done: 0.mp4 | processed=1799, saved=1799, failed=0
✅ Saved: /kaggle/working/features/features_24.csv

 18%|█▊        | 26/141 [54:06<4:47:48, 150.17s/it]

Done: 10.MOV | processed=1493, saved=1493, failed=0
✅ Saved: /kaggle/working/features/features_25.csv

 19%|█▉        | 27/141 [56:07<4:28:32, 141.34s/it]

Done: 0.MOV | processed=1806, saved=1806, failed=0
✅ Saved: /kaggle/working/features/features_26.csv

 20%|█▉        | 28/141 [57:46<4:02:33, 128.79s/it]

Done: 5.MOV | processed=1451, saved=1451, failed=0
✅ Saved: /kaggle/working/features/features_27.csv

 21%|██        | 29/141 [1:01:56<5:08:11, 165.11s/it]

Done: 5.mp4 | processed=2644, saved=2644, failed=0
✅ Saved: /kaggle/working/features/features_28.csv

 21%|██▏       | 30/141 [1:05:48<5:42:40, 185.23s/it]

Done: 10.mp4 | processed=2084, saved=2078, failed=6
✅ Saved: /kaggle/working/features/features_29.csv

 22%|██▏       | 31/141 [1:07:56<5:07:53, 167.94s/it]

Done: 0.mp4 | processed=1848, saved=1848, failed=0
✅ Saved: /kaggle/working/features/features_30.csv

 23%|██▎       | 32/141 [1:10:33<4:59:08, 164.67s/it]

Done: 5.mp4 | processed=2084, saved=2084, failed=0
✅ Saved: /kaggle/working/features/features_31.csv

 23%|██▎       | 33/141 [1:14:04<5:21:15, 178.48s/it]

Done: 10.mp4 | processed=1825, saved=1825, failed=0
✅ Saved: /kaggle/working/features/features_32.csv

 24%|██▍       | 34/141 [1:16:32<5:01:56, 169.31s/it]

Done: 0.mp4 | processed=2043, saved=2043, failed=0
✅ Saved: /kaggle/working/features/features_33.csv

 25%|██▍       | 35/141 [1:17:32<4:01:12, 136.54s/it]

Done: 5.mp4 | processed=817, saved=817, failed=0
✅ Saved: /kaggle/working/features/features_34.csv

 26%|██▌       | 36/141 [1:18:39<3:22:33, 115.75s/it]

Done: 10.mp4 | processed=1071, saved=1071, failed=0
✅ Saved: /kaggle/working/features/features_35.csv

 26%|██▌       | 37/141 [1:20:39<3:22:36, 116.89s/it]

Done: 0.mp4 | processed=1916, saved=1916, failed=0
✅ Saved: /kaggle/working/features/features_36.csv

 27%|██▋       | 38/141 [1:24:26<4:17:48, 150.18s/it]

Done: 10.MOV | processed=1806, saved=1806, failed=0
✅ Saved: /kaggle/working/features/features_37.csv

 28%|██▊       | 39/141 [1:28:09<4:52:05, 171.82s/it]

Done: 0.MOV | processed=1802, saved=1802, failed=0
✅ Saved: /kaggle/working/features/features_38.csv

 28%|██▊       | 40/141 [1:32:09<5:23:38, 192.26s/it]

Done: 5.MOV | processed=1803, saved=1803, failed=0
✅ Saved: /kaggle/working/features/features_39.csv

 29%|██▉       | 41/141 [1:35:53<5:36:42, 202.02s/it]

Done: 10.MOV | processed=1831, saved=1831, failed=0
✅ Saved: /kaggle/working/features/features_40.csv

 30%|██▉       | 42/141 [1:39:44<5:47:34, 210.65s/it]

Done: 0.MOV | processed=1822, saved=1822, failed=0
✅ Saved: /kaggle/working/features/features_41.csv

 30%|███       | 43/141 [1:43:44<5:58:10, 219.29s/it]

Done: 5.MOV | processed=1826, saved=1826, failed=0
✅ Saved: /kaggle/working/features/features_42.csv

 31%|███       | 44/141 [1:44:55<4:42:47, 174.92s/it]

Done: 5.mp4 | processed=1730, saved=1354, failed=376
✅ Saved: /kaggle/working/features/features_43.csv

 32%|███▏      | 45/141 [1:46:07<3:50:16, 143.92s/it]

Done: 10.mp4 | processed=1818, saved=901, failed=917
✅ Saved: /kaggle/working/features/features_44.csv

 33%|███▎      | 46/141 [1:46:59<3:04:21, 116.43s/it]

Done: 0.mp4 | processed=1756, saved=286, failed=1470
✅ Saved: /kaggle/working/features/features_45.csv

 33%|███▎      | 47/141 [1:48:05<2:38:50, 101.39s/it]

Done: 10.mp4 | processed=2152, saved=2137, failed=15
✅ Saved: /kaggle/working/features/features_46.csv

 34%|███▍      | 48/141 [1:50:56<3:09:36, 122.32s/it]

Done: 0.mp4 | processed=1958, saved=1942, failed=16
✅ Saved: /kaggle/working/features/features_47.csv

 35%|███▍      | 49/141 [1:54:07<3:38:52, 142.75s/it]

Done: 5.MOV | processed=1820, saved=1810, failed=10
✅ Saved: /kaggle/working/features/features_48.csv

 35%|███▌      | 50/141 [1:56:00<3:22:49, 133.73s/it]

Done: 10.MOV | processed=1805, saved=1805, failed=0
✅ Saved: /kaggle/working/features/features_49.csv

 36%|███▌      | 51/141 [1:57:58<3:13:51, 129.24s/it]

Done: 0.MOV | processed=1815, saved=1815, failed=0
✅ Saved: /kaggle/working/features/features_50.csv

 37%|███▋      | 52/141 [2:00:01<3:08:55, 127.37s/it]

Done: 5.MOV | processed=1803, saved=1803, failed=0
✅ Saved: /kaggle/working/features/features_51.csv

 38%|███▊      | 53/141 [2:01:41<2:54:35, 119.04s/it]

Done: 5.mp4 | processed=1093, saved=1093, failed=0
✅ Saved: /kaggle/working/features/features_52.csv

 38%|███▊      | 54/141 [2:03:23<2:45:05, 113.86s/it]

Done: 10.mp4 | processed=1151, saved=1151, failed=0
✅ Saved: /kaggle/working/features/features_53.csv

 39%|███▉      | 55/141 [2:04:58<2:35:16, 108.33s/it]

Done: 0.mp4 | processed=1104, saved=1104, failed=0
✅ Saved: /kaggle/working/features/features_54.csv

 40%|███▉      | 56/141 [2:07:55<3:02:43, 128.98s/it]

Done: 5.mp4 | processed=1788, saved=1788, failed=0
✅ Saved: /kaggle/working/features/features_55.csv

 40%|████      | 57/141 [2:11:25<3:34:26, 153.17s/it]

Done: 10.mp4 | processed=1793, saved=1793, failed=0
✅ Saved: /kaggle/working/features/features_56.csv

 41%|████      | 58/141 [2:14:53<3:54:48, 169.75s/it]

Done: 0.mp4 | processed=1801, saved=1801, failed=0
✅ Saved: /kaggle/working/features/features_57.csv

 42%|████▏     | 59/141 [2:17:05<3:36:23, 158.33s/it]

Done: 10.MOV | processed=1886, saved=1886, failed=0
✅ Saved: /kaggle/working/features/features_58.csv

 43%|████▎     | 60/141 [2:17:53<2:49:06, 125.26s/it]

Done: 0.MOV | processed=1630, saved=1630, failed=0
✅ Saved: /kaggle/working/features/features_59.csv

 43%|████▎     | 61/141 [2:19:56<2:45:53, 124.41s/it]

Done: 5.MOV | processed=1862, saved=1862, failed=0
✅ Saved: /kaggle/working/features/features_60.csv

 44%|████▍     | 62/141 [2:21:47<2:38:38, 120.49s/it]

Done: 5.mp4 | processed=1883, saved=1883, failed=0
✅ Saved: /kaggle/working/features/features_61.csv

 45%|████▍     | 63/141 [2:23:24<2:27:33, 113.51s/it]

Done: 10.mp4 | processed=1509, saved=1505, failed=4
✅ Saved: /kaggle/working/features/features_62.csv

 45%|████▌     | 64/141 [2:25:00<2:19:00, 108.32s/it]

Done: 0.mp4 | processed=1691, saved=1691, failed=0
✅ Saved: /kaggle/working/features/features_63.csv

 46%|████▌     | 65/141 [2:28:02<2:45:08, 130.38s/it]

Done: 5.mp4 | processed=1804, saved=1802, failed=2
✅ Saved: /kaggle/working/features/features_64.csv

 47%|████▋     | 66/141 [2:30:59<3:00:15, 144.21s/it]

Done: 10.mp4 | processed=1798, saved=1788, failed=10
✅ Saved: /kaggle/working/features/features_65.csv

 48%|████▊     | 67/141 [2:32:04<2:28:30, 120.41s/it]

Done: 0.mp4 | processed=1815, saved=1815, failed=0
✅ Saved: /kaggle/working/features/features_66.csv

 48%|████▊     | 68/141 [2:36:17<3:15:07, 160.37s/it]

Done: 5.mp4 | processed=1836, saved=1836, failed=0
✅ Saved: /kaggle/working/features/features_67.csv

 49%|████▉     | 69/141 [2:40:33<3:46:51, 189.05s/it]

Done: 10.mp4 | processed=1981, saved=1981, failed=0
✅ Saved: /kaggle/working/features/features_68.csv

 50%|████▉     | 70/141 [2:44:21<3:57:34, 200.77s/it]

Done: 0.mp4 | processed=1817, saved=1813, failed=4
✅ Saved: /kaggle/working/features/features_69.csv

 50%|█████     | 71/141 [2:45:20<3:04:39, 158.28s/it]

Done: 5.mp4 | processed=985, saved=982, failed=3
✅ Saved: /kaggle/working/features/features_70.csv

 51%|█████     | 72/141 [2:46:24<2:29:18, 129.83s/it]

Done: 10.mp4 | processed=1065, saved=1064, failed=1
✅ Saved: /kaggle/working/features/features_71.csv

 52%|█████▏    | 73/141 [2:48:04<2:17:05, 120.97s/it]

Done: 0.mp4 | processed=1881, saved=1881, failed=0
✅ Saved: /kaggle/working/features/features_72.csv

 52%|█████▏    | 74/141 [2:50:05<2:15:04, 120.96s/it]

Done: 10.MOV | processed=1805, saved=1805, failed=0
✅ Saved: /kaggle/working/features/features_73.csv

 53%|█████▎    | 75/141 [2:51:58<2:10:17, 118.45s/it]

Done: 0.MOV | processed=1841, saved=1841, failed=0
✅ Saved: /kaggle/working/features/features_74.csv

 54%|█████▍    | 76/141 [2:54:00<2:09:40, 119.70s/it]

Done: 5.MOV | processed=1806, saved=1806, failed=0
✅ Saved: /kaggle/working/features/features_75.csv

 55%|█████▍    | 77/141 [2:56:05<2:09:15, 121.18s/it]

Done: 5.mp4 | processed=1311, saved=1311, failed=0
✅ Saved: /kaggle/working/features/features_76.csv

 55%|█████▌    | 78/141 [2:57:50<2:02:01, 116.22s/it]

Done: 10.mp4 | processed=1023, saved=1023, failed=0
✅ Saved: /kaggle/working/features/features_77.csv

 56%|█████▌    | 79/141 [3:00:24<2:12:06, 127.84s/it]

Done: 0.mp4 | processed=1523, saved=1523, failed=0
✅ Saved: /kaggle/working/features/features_78.csv

 57%|█████▋    | 80/141 [3:04:33<2:46:49, 164.09s/it]

Done: 10.MOV | processed=1812, saved=1812, failed=0
✅ Saved: /kaggle/working/features/features_79.csv

 57%|█████▋    | 81/141 [3:07:27<2:47:05, 167.09s/it]

Done: 0.mov | processed=1826, saved=1826, failed=0
✅ Saved: /kaggle/working/features/features_80.csv

 58%|█████▊    | 82/141 [3:11:26<3:05:31, 188.67s/it]

Done: 5.MOV | processed=1810, saved=1810, failed=0
✅ Saved: /kaggle/working/features/features_81.csv

 59%|█████▉    | 83/141 [3:13:16<2:39:22, 164.88s/it]

Done: 5.mp4 | processed=1822, saved=1808, failed=14
✅ Saved: /kaggle/working/features/features_82.csv

 60%|█████▉    | 84/141 [3:14:24<2:09:06, 135.89s/it]

Done: 10.mp4 | processed=1539, saved=1539, failed=0
✅ Saved: /kaggle/working/features/features_83.csv

 60%|██████    | 85/141 [3:15:18<1:43:58, 111.40s/it]

Done: 0.mp4 | processed=1536, saved=1536, failed=0
✅ Saved: /kaggle/working/features/features_84.csv

 61%|██████    | 86/141 [3:17:06<1:41:12, 110.41s/it]

Done: 10.mov | processed=1848, saved=1848, failed=0
✅ Saved: /kaggle/working/features/features_85.csv

 62%|██████▏   | 87/141 [3:21:23<2:18:56, 154.38s/it]

Done: 0.MOV | processed=2076, saved=2076, failed=0
✅ Saved: /kaggle/working/features/features_86.csv

 62%|██████▏   | 88/141 [3:23:09<2:03:23, 139.69s/it]

Done: 5.mov | processed=1851, saved=1851, failed=0
✅ Saved: /kaggle/working/features/features_87.csv

 63%|██████▎   | 89/141 [3:25:39<2:03:55, 143.00s/it]

Done: 10.MOV | processed=1801, saved=1801, failed=0
✅ Saved: /kaggle/working/features/features_88.csv

 64%|██████▍   | 90/141 [3:29:37<2:25:40, 171.38s/it]

Done: 0.mov | processed=1805, saved=1805, failed=0
✅ Saved: /kaggle/working/features/features_89.csv

 65%|██████▍   | 91/141 [3:32:13<2:18:57, 166.75s/it]

Done: 5.mov | processed=1796, saved=1796, failed=0
✅ Saved: /kaggle/working/features/features_90.csv

 65%|██████▌   | 92/141 [3:34:43<2:11:59, 161.62s/it]

Done: 5.mp4 | processed=1829, saved=1829, failed=0
✅ Saved: /kaggle/working/features/features_91.csv

 66%|██████▌   | 93/141 [3:37:20<2:08:17, 160.36s/it]

Done: 10.mp4 | processed=1990, saved=1990, failed=0
✅ Saved: /kaggle/working/features/features_92.csv

 67%|██████▋   | 94/141 [3:40:00<2:05:31, 160.25s/it]

Done: 0.mp4 | processed=1856, saved=1851, failed=5
✅ Saved: /kaggle/working/features/features_93.csv

 67%|██████▋   | 95/141 [3:42:03<1:54:13, 148.98s/it]

Done: 5.mp4 | processed=1879, saved=1879, failed=0
✅ Saved: /kaggle/working/features/features_94.csv

 68%|██████▊   | 96/141 [3:44:02<1:45:08, 140.19s/it]

Done: 10.mp4 | processed=1872, saved=1872, failed=0
✅ Saved: /kaggle/working/features/features_95.csv

 69%|██████▉   | 97/141 [3:45:40<1:33:25, 127.41s/it]

Done: 0.mp4 | processed=1869, saved=1869, failed=0
✅ Saved: /kaggle/working/features/features_96.csv

 70%|██████▉   | 98/141 [3:47:28<1:27:04, 121.50s/it]

Done: 5.mp4 | processed=1378, saved=1378, failed=0
✅ Saved: /kaggle/working/features/features_97.csv

 70%|███████   | 99/141 [3:49:02<1:19:15, 113.22s/it]

Done: 0.mp4 | processed=1078, saved=1078, failed=0
✅ Saved: /kaggle/working/features/features_98.csv

 71%|███████   | 100/141 [3:50:23<1:10:51, 103.71s/it]

Done: 5.mp4 | processed=1514, saved=1514, failed=0
✅ Saved: /kaggle/working/features/features_99.csv

 72%|███████▏  | 101/141 [3:51:48<1:05:26, 98.17s/it]

Done: 10.mp4 | processed=1612, saved=1612, failed=0
✅ Saved: /kaggle/working/features/features_100.csv

 72%|███████▏  | 102/141 [3:53:18<1:02:10, 95.66s/it]

Done: 0.mp4 | processed=1700, saved=1700, failed=0
✅ Saved: /kaggle/working/features/features_101.csv

 73%|███████▎  | 103/141 [3:54:19<53:56, 85.16s/it]

Done: 10.mp4 | processed=1838, saved=1838, failed=0
✅ Saved: /kaggle/working/features/features_102.csv

 74%|███████▍  | 104/141 [3:55:29<49:43, 80.62s/it]

Done: 0.mov | processed=1162, saved=1162, failed=0
✅ Saved: /kaggle/working/features/features_103.csv

 74%|███████▍  | 105/141 [3:57:42<57:49, 96.37s/it]

Done: 5.mov | processed=2069, saved=2069, failed=0
✅ Saved: /kaggle/working/features/features_104.csv

 75%|███████▌  | 106/141 [3:58:56<52:20, 89.72s/it]

Done: 5.mp4 | processed=905, saved=902, failed=3
✅ Saved: /kaggle/working/features/features_105.csv

 76%|███████▌  | 107/141 [4:00:47<54:30, 96.19s/it]

Done: 10.mp4 | processed=1680, saved=1670, failed=10
✅ Saved: /kaggle/working/features/features_106.csv

 77%|███████▋  | 108/141 [4:02:40<55:39, 101.19s/it]

Done: 0.mp4 | processed=1765, saved=1765, failed=0
✅ Saved: /kaggle/working/features/features_107.csv

 77%|███████▋  | 109/141 [4:03:50<48:54, 91.72s/it]

Done: 5.mp4 | processed=1077, saved=1077, failed=0
✅ Saved: /kaggle/working/features/features_108.csv

 78%|███████▊  | 110/141 [4:12:10<1:50:41, 214.24s/it]

Done: 10.MOV | processed=2832, saved=2832, failed=0
✅ Saved: /kaggle/working/features/features_109.csv

 79%|███████▊  | 111/141 [4:13:33<1:27:28, 174.97s/it]

Done: 0.MP4 | processed=1883, saved=1883, failed=0
✅ Saved: /kaggle/working/features/features_110.csv

 79%|███████▉  | 112/141 [4:16:42<1:26:29, 178.96s/it]

Done: 10.MOV | processed=1815, saved=1815, failed=0
✅ Saved: /kaggle/working/features/features_111.csv

 80%|████████  | 113/141 [4:20:15<1:28:18, 189.23s/it]

Done: 0.MP4 | processed=1937, saved=1937, failed=0
✅ Saved: /kaggle/working/features/features_112.csv

 81%|████████  | 114/141 [4:23:35<1:26:40, 192.60s/it]

Done: 5.MOV | processed=1817, saved=1816, failed=1
✅ Saved: /kaggle/working/features/features_113.csv

 82%|████████▏ | 115/141 [4:25:23<1:12:22, 167.03s/it]

Done: 5.mp4 | processed=1809, saved=1809, failed=0
✅ Saved: /kaggle/working/features/features_114.csv

 82%|████████▏ | 116/141 [4:28:44<1:13:56, 177.47s/it]

Done: 10.mp4 | processed=1806, saved=1806, failed=0
✅ Saved: /kaggle/working/features/features_115.csv

 83%|████████▎ | 117/141 [4:32:18<1:15:17, 188.23s/it]

Done: 0.mp4 | processed=1805, saved=1805, failed=0
✅ Saved: /kaggle/working/features/features_116.csv

 84%|████████▎ | 118/141 [4:34:10<1:03:27, 165.53s/it]

Done: 5.mp4 | processed=1803, saved=1803, failed=0
✅ Saved: /kaggle/working/features/features_117.csv

 84%|████████▍ | 119/141 [4:36:13<55:57, 152.62s/it]

Done: 10.mp4 | processed=1802, saved=1802, failed=0
✅ Saved: /kaggle/working/features/features_118.csv

 85%|████████▌ | 120/141 [4:38:06<49:16, 140.77s/it]

Done: 0.mp4 | processed=1806, saved=1806, failed=0
✅ Saved: /kaggle/working/features/features_119.csv

 86%|████████▌ | 121/141 [4:40:02<44:26, 133.30s/it]

Done: 10.mov | processed=2039, saved=2034, failed=5
✅ Saved: /kaggle/working/features/features_120.csv

 87%|████████▋ | 122/141 [4:42:04<41:11, 130.09s/it]

Done: 0.mov | processed=2048, saved=2048, failed=0
✅ Saved: /kaggle/working/features/features_121.csv

 87%|████████▋ | 123/141 [4:44:05<38:08, 127.16s/it]

Done: 5.mov | processed=1855, saved=1855, failed=0
✅ Saved: /kaggle/working/features/features_122.csv

 88%|████████▊ | 124/141 [4:46:06<35:31, 125.37s/it]

Done: 5.mp4 | processed=1824, saved=1824, failed=0
✅ Saved: /kaggle/working/features/features_123.csv

 89%|████████▊ | 125/141 [4:46:56<27:26, 102.89s/it]

Done: 10.mp4 | processed=1821, saved=1817, failed=4
✅ Saved: /kaggle/working/features/features_124.csv

 89%|████████▉ | 126/141 [4:47:54<22:21, 89.41s/it]

Done: 0.mp4 | processed=1812, saved=1812, failed=0
✅ Saved: /kaggle/working/features/features_125.csv

 90%|█████████ | 127/141 [4:48:43<18:01, 77.28s/it]

Done: 10.mov | processed=767, saved=767, failed=0
✅ Saved: /kaggle/working/features/features_126.csv

 91%|█████████ | 128/141 [4:49:55<16:22, 75.59s/it]

Done: 0.mov | processed=1167, saved=1167, failed=0
✅ Saved: /kaggle/working/features/features_127.csv

 91%|█████████▏| 129/141 [4:50:48<13:44, 68.73s/it]

Done: 5.mov | processed=897, saved=897, failed=0
✅ Saved: /kaggle/working/features/features_128.csv

 92%|█████████▏| 130/141 [4:52:14<13:35, 74.12s/it]

Done: 10.MOV | processed=1449, saved=1448, failed=1
✅ Saved: /kaggle/working/features/features_129.csv

 93%|█████████▎| 131/141 [4:53:32<12:31, 75.17s/it]

Done: 0.MOV | processed=1135, saved=1135, failed=0
✅ Saved: /kaggle/working/features/features_130.csv

 94%|█████████▎| 132/141 [4:55:02<11:55, 79.54s/it]

Done: 5.MOV | processed=1448, saved=1448, failed=0
✅ Saved: /kaggle/working/features/features_131.csv

 94%|█████████▍| 133/141 [4:59:09<17:18, 129.87s/it]

Done: 5.mp4 | processed=2047, saved=2047, failed=0
✅ Saved: /kaggle/working/features/features_132.csv

 95%|█████████▌| 134/141 [5:02:57<18:34, 159.20s/it]

Done: 10.mp4 | processed=1848, saved=1848, failed=0
✅ Saved: /kaggle/working/features/features_133.csv

 96%|█████████▌| 135/141 [5:06:42<17:55, 179.17s/it]

Done: 0.mp4 | processed=1823, saved=1818, failed=5
✅ Saved: /kaggle/working/features/features_134.csv

 96%|█████████▋| 136/141 [5:08:46<13:32, 162.55s/it]

Done: 5.mp4 | processed=1854, saved=1854, failed=0
✅ Saved: /kaggle/working/features/features_135.csv

 97%|█████████▋| 137/141 [5:10:49<10:02, 150.54s/it]

Done: 10.mp4 | processed=1848, saved=1848, failed=0
✅ Saved: /kaggle/working/features/features_136.csv

 98%|█████████▊| 138/141 [5:12:56<07:10, 143.46s/it]

Done: 0.mp4 | processed=1930, saved=1924, failed=6
✅ Saved: /kaggle/working/features/features_137.csv

 99%|█████████▊| 139/141 [5:15:02<04:36, 138.20s/it]

Done: 5.mp4 | processed=1974, saved=1974, failed=0
✅ Saved: /kaggle/working/features/features_138.csv

 99%|█████████▉| 140/141 [5:18:42<02:42, 162.94s/it]

Done: 10.mp4 | processed=1869, saved=1869, failed=0
✅ Saved: /kaggle/working/features/features_139.csv

100%|██████████| 141/141 [5:23:54<00:00, 137.83s/it]

Done: 0.mp4 | processed=1838, saved=1838, failed=0
✅ Saved: /kaggle/working/features/features_140.csv

In [16]:
import glob

files = glob.glob("/kaggle/working/features/*.csv")

df_list = [pd.read_csv(f) for f in files]

features_df = pd.concat(df_list, ignore_index=True)

print("Total rows:", len(features_df))

Total rows: 235706

In [18]:
import glob
import pandas as pd
import os

# Folder where individual feature CSVs are saved
features_dir = "/kaggle/working/features"

# Output concatenated CSV file
output_file = "/kaggle/working/features_progress.csv"

# Get all CSV files
files = glob.glob(os.path.join(features_dir, "*.csv"))

print("Number of files found:", len(files))

# Read and concatenate
df_list = [pd.read_csv(f) for f in files]

features_df = pd.concat(df_list, ignore_index=True)

print("Total rows:", len(features_df))

# Save concatenated file
features_df.to_csv(output_file, index=False)

print(f"✅ Concatenated feature file saved at: {output_file}")

Number of files found: 141
Total rows: 235706
✅ Concatenated feature file saved at: /kaggle/working/features_progress.csv

In [19]:
features_df = pd.read_csv("/kaggle/working/features_progress.csv")

numeric_cols = ["EAR", "MAR", "pitch", "yaw"]

baseline = (
    features_df[features_df["label"] == "Alert"]
    .groupby("subject")[numeric_cols]
    .mean()
)

def normalize(row):
    subject = row["subject"]

    if subject in baseline.index:
        row["EAR_dev"] = row["EAR"] - baseline.loc[subject, "EAR"]
        row["MAR_dev"] = row["MAR"] - baseline.loc[subject, "MAR"]
    else:
        row["EAR_dev"] = row["EAR"]
        row["MAR_dev"] = row["MAR"]

    return row

features_df = features_df.apply(normalize, axis=1)

display(features_df.head())
features_df.to_csv("/kaggle/working/features_normalized.csv", index=False)

print("✅ Saved normalized features file")

,subject,label,frame,EAR,MAR,pitch,yaw,video_path,EAR_dev,MAR_dev
0,20,Low Vigilance,30,0.265168,0.093651,476.009454,748.818403,/kaggle/input/datasets/rishab260/uta-reallife-...,0.011799,0.084260
1,20,Low Vigilance,40,0.193316,0.003777,458.795161,741.967654,/kaggle/input/datasets/rishab260/uta-reallife-...,-0.060053,-0.005614
2,20,Low Vigilance,50,0.209924,0.021052,417.269697,681.898819,/kaggle/input/datasets/rishab260/uta-reallife-...,-0.043445,0.011661
3,20,Low Vigilance,60,0.200726,0.034570,373.262642,636.804523,/kaggle/input/datasets/rishab260/uta-reallife-...,-0.052643,0.025179
4,20,Low Vigilance,70,0.189407,0.006242,360.013889,629.407658,/kaggle/input/datasets/rishab260/uta-reallife-...,-0.063962,-0.003149

✅ Saved normalized features file

In [20]:
window_size = 15
windows = []

for subject in features_df["subject"].unique():
    sub_df = features_df[features_df["subject"] == subject].copy()
    sub_df = sub_df.sort_values(["video_path", "frame"])

    for video_path in sub_df["video_path"].unique():
        vid_df = sub_df[sub_df["video_path"] == video_path]

        for i in range(len(vid_df) - window_size):
            chunk = vid_df.iloc[i:i + window_size]

            windows.append({
                "subject": subject,
                "video_path": video_path,
                "label": chunk["label"].iloc[0],
                "EAR_mean": chunk["EAR"].mean(),
                "EAR_std": chunk["EAR"].std(),
                "EAR_min": chunk["EAR"].min(),
                "MAR_mean": chunk["MAR"].mean(),
                "MAR_max": chunk["MAR"].max(),
                "pitch_mean": chunk["pitch"].mean(),
                "yaw_mean": chunk["yaw"].mean(),
                "EAR_dev_mean": chunk["EAR_dev"].mean(),
                "MAR_dev_mean": chunk["MAR_dev"].mean()
            })

window_df = pd.DataFrame(windows)

print("Window rows:", len(window_df))
display(window_df.head())
window_df.to_csv("/kaggle/working/window_features.csv", index=False)

print("✅ Saved window features: /kaggle/working/window_features.csv")

Window rows: 233591

,subject,video_path,label,EAR_mean,EAR_std,EAR_min,MAR_mean,MAR_max,pitch_mean,yaw_mean,EAR_dev_mean,MAR_dev_mean
0,20,/kaggle/input/datasets/rishab260/uta-reallife-...,Alert,0.237036,0.037249,0.137103,0.036132,0.199047,370.103525,635.342636,-0.016333,0.026740
1,20,/kaggle/input/datasets/rishab260/uta-reallife-...,Alert,0.247254,0.045480,0.137103,0.035163,0.199047,332.952045,581.059837,-0.006115,0.025772
2,20,/kaggle/input/datasets/rishab260/uta-reallife-...,Alert,0.252945,0.050826,0.137103,0.029647,0.199047,327.099773,572.753631,-0.000425,0.020256
3,20,/kaggle/input/datasets/rishab260/uta-reallife-...,Alert,0.257431,0.055144,0.137103,0.030483,0.199047,314.021163,556.392134,0.004062,0.021092
4,20,/kaggle/input/datasets/rishab260/uta-reallife-...,Alert,0.256823,0.055100,0.137103,0.018152,0.042090,303.104617,530.404469,0.003454,0.008761

✅ Saved window features: /kaggle/working/window_features.csv

In [21]:
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import joblib

le = LabelEncoder()
window_df["y"] = le.fit_transform(window_df["label"])

drop_cols = ["label", "y", "subject", "video_path"]
X = window_df.drop(drop_cols, axis=1)
y = window_df["y"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

print(classification_report(
    y_test,
    pred,
    target_names=le.classes_
))

# Save model, label encoder, and feature columns
joblib.dump(model, "/kaggle/working/random_forest_model.pkl")
joblib.dump(le, "/kaggle/working/label_encoder.pkl")
joblib.dump(X.columns.tolist(), "/kaggle/working/feature_columns.pkl")

print("✅ Model saved: /kaggle/working/random_forest_model.pkl")
print("✅ Label encoder saved: /kaggle/working/label_encoder.pkl")
print("✅ Feature columns saved: /kaggle/working/feature_columns.pkl")

               precision    recall  f1-score   support

        Alert       1.00      1.00      1.00     15619
       Drowsy       1.00      1.00      1.00     15693
Low Vigilance       1.00      1.00      1.00     15407

     accuracy                           1.00     46719
    macro avg       1.00      1.00      1.00     46719
 weighted avg       1.00      1.00      1.00     46719

✅ Model saved: /kaggle/working/random_forest_model.pkl
✅ Label encoder saved: /kaggle/working/label_encoder.pkl
✅ Feature columns saved: /kaggle/working/feature_columns.pkl

In [22]:
report = classification_report(
    y_test,
    pred,
    target_names=le.classes_
)

print(report)

with open("/kaggle/working/classification_report.txt", "w") as f:
    f.write(report)

print("✅ Classification report saved")

               precision    recall  f1-score   support

        Alert       1.00      1.00      1.00     15619
       Drowsy       1.00      1.00      1.00     15693
Low Vigilance       1.00      1.00      1.00     15407

     accuracy                           1.00     46719
    macro avg       1.00      1.00      1.00     46719
 weighted avg       1.00      1.00      1.00     46719

✅ Classification report saved

In [23]:
pred = model.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, pred)

print("Accuracy:", accuracy)
print("Accuracy percentage:", accuracy * 100, "%")

Accuracy: 0.9962113915109484
Accuracy percentage: 99.62113915109484 %

In [25]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, pred)

print(f"✅ Model Accuracy: {accuracy:.4f}")
print(f"✅ Model Accuracy Percentage: {accuracy * 100:.2f}%")

✅ Model Accuracy: 0.9962
✅ Model Accuracy Percentage: 99.62%

In [26]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, pred)

accuracy_text = f"Model Accuracy: {accuracy:.4f}\nModel Accuracy Percentage: {accuracy * 100:.2f}%"

print(accuracy_text)

with open("/kaggle/working/accuracy.txt", "w") as f:
    f.write(accuracy_text)

print("✅ Accuracy saved at: /kaggle/working/accuracy.txt")

Model Accuracy: 0.9962
Model Accuracy Percentage: 99.62%
✅ Accuracy saved at: /kaggle/working/accuracy.txt

In [27]:
accuracy = model.score(X_test, y_test)

print(f"Accuracy: {accuracy:.4f}")
print(f"Accuracy Percentage: {accuracy * 100:.2f}%")

Accuracy: 0.9962
Accuracy Percentage: 99.62%

In [28]:
from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

accuracy = accuracy_score(y_test, pred)

print("=" * 40)
print(f"✅ Final Test Accuracy: {accuracy:.4f}")
print(f"✅ Final Test Accuracy Percentage: {accuracy * 100:.2f}%")
print("=" * 40)

========================================
✅ Final Test Accuracy: 0.9962
✅ Final Test Accuracy Percentage: 99.62%
========================================

In [30]:
import pandas as pd

features_df = pd.read_csv("/kaggle/working/features_progress.csv")

numeric_cols = ["EAR", "MAR", "pitch", "yaw"]

baseline = (
    features_df[features_df["label"] == "Alert"]
    .groupby("subject")[numeric_cols]
    .mean()
)

baseline.to_csv("/kaggle/working/baseline_by_subject.csv")

print("✅ Baseline saved at: /kaggle/working/baseline_by_subject.csv")
display(baseline.head())

✅ Baseline saved at: /kaggle/working/baseline_by_subject.csv

              EAR       MAR       pitch         yaw
subject
1        0.303734  0.010927  230.098915  369.902234
2        0.301671  0.014962  205.900822  324.892506
3        0.283038  0.010225  203.785617  368.570744
4        0.296292  0.013034   97.361923  160.952923
5        0.327134  0.012007  194.941465  308.112217

In [31]:
import joblib
import pandas as pd
import numpy as np
from collections import Counter

model = joblib.load("/kaggle/working/random_forest_model.pkl")
le = joblib.load("/kaggle/working/label_encoder.pkl")
feature_columns = joblib.load("/kaggle/working/feature_columns.pkl")

baseline = pd.read_csv("/kaggle/working/baseline_by_subject.csv", index_col=0)

print("✅ Model loaded")
print("Classes:", le.classes_)
print("Feature columns:", feature_columns)

✅ Model loaded
Classes: ['Alert' 'Drowsy' 'Low Vigilance']
Feature columns: ['EAR_mean', 'EAR_std', 'EAR_min', 'MAR_mean', 'MAR_max', 'pitch_mean', 'yaw_mean', 'EAR_dev_mean', 'MAR_dev_mean']

In [32]:
def normalize_test_features(features_df, subject):
    """
    Adds EAR_dev and MAR_dev to test video features.
    If subject exists in training baseline, use that baseline.
    Otherwise use raw EAR and MAR as fallback.
    """

    features_df = features_df.copy()

    if subject in baseline.index:
        features_df["EAR_dev"] = features_df["EAR"] - baseline.loc[subject, "EAR"]
        features_df["MAR_dev"] = features_df["MAR"] - baseline.loc[subject, "MAR"]
        print(f"✅ Used baseline for subject: {subject}")
    else:
        features_df["EAR_dev"] = features_df["EAR"]
        features_df["MAR_dev"] = features_df["MAR"]
        print(f"⚠️ No baseline found for subject: {subject}. Using raw EAR/MAR.")

    return features_df

In [33]:
def create_test_windows(features_df, window_size=15):
    windows = []

    features_df = features_df.sort_values(["video_path", "frame"])

    for video_path in features_df["video_path"].unique():
        vid_df = features_df[features_df["video_path"] == video_path]

        if len(vid_df) < window_size:
            print(f"❌ Not enough frames. Need at least {window_size}, got {len(vid_df)}")
            return pd.DataFrame()

        for i in range(len(vid_df) - window_size + 1):
            chunk = vid_df.iloc[i:i + window_size]

            windows.append({
                "EAR_mean": chunk["EAR"].mean(),
                "EAR_std": chunk["EAR"].std(),
                "EAR_min": chunk["EAR"].min(),
                "MAR_mean": chunk["MAR"].mean(),
                "MAR_max": chunk["MAR"].max(),
                "pitch_mean": chunk["pitch"].mean(),
                "yaw_mean": chunk["yaw"].mean(),
                "EAR_dev_mean": chunk["EAR_dev"].mean(),
                "MAR_dev_mean": chunk["MAR_dev"].mean()
            })

    window_df = pd.DataFrame(windows)

    return window_df

In [34]:
def predict_video(video_path, subject="test_subject", sample_rate=10, window_size=15):
    """
    Predicts Alert / Low Vigilance / Drowsy for a new video.
    """

    print("Processing video:", video_path)

    rows = process_video(
        path=video_path,
        label="Unknown",
        subject=subject,
        sample_rate=sample_rate
    )

    frame_features = pd.DataFrame(rows)

    if len(frame_features) == 0:
        print("❌ No face/features extracted from video.")
        return None

    print("Extracted frame features:", len(frame_features))

    frame_features = normalize_test_features(frame_features, subject)

    window_features = create_test_windows(
        frame_features,
        window_size=window_size
    )

    if len(window_features) == 0:
        print("❌ No windows created.")
        return None

    print("Created windows:", len(window_features))

    X_new = window_features[feature_columns]

    pred_encoded = model.predict(X_new)
    pred_labels = le.inverse_transform(pred_encoded)

    window_features["prediction"] = pred_labels

    if hasattr(model, "predict_proba"):
        probs = model.predict_proba(X_new)
        avg_probs = probs.mean(axis=0)

        prob_df = pd.DataFrame({
            "class": le.classes_,
            "average_probability": avg_probs
        }).sort_values("average_probability", ascending=False)

        print("\nAverage class probabilities:")
        display(prob_df)

    counts = Counter(pred_labels)

    print("\nWindow prediction counts:")
    for cls, count in counts.items():
        print(f"{cls}: {count}")

    final_prediction = counts.most_common(1)[0][0]

    print("\n" + "=" * 40)
    print(f"✅ Final Video Prediction: {final_prediction}")
    print("=" * 40)

    return final_prediction, window_features

In [35]:
test_video_path = "/kaggle/input/datasets/rishab260/uta-reallife-drowsiness-dataset/10_1.mp4"

final_prediction, prediction_windows = predict_video(
    video_path=test_video_path,
    subject="test_subject",
    sample_rate=10,
    window_size=15
)

Processing video: /kaggle/input/datasets/rishab260/uta-reallife-drowsiness-dataset/10_1.mp4
Could not open video: /kaggle/input/datasets/rishab260/uta-reallife-drowsiness-dataset/10_1.mp4
❌ No face/features extracted from video.

TypeError: cannot unpack non-iterable NoneType object

In [37]:
df = pd.read_csv("/kaggle/working/metadata_clean.csv")

sample_video = df.iloc[0]["path"]
sample_subject = df.iloc[0]["subject"]

print(sample_video)
print(sample_subject)

final_prediction, prediction_windows = predict_video(
    video_path=sample_video,
    subject=sample_subject,
    sample_rate=10,
    window_size=15
)

/kaggle/input/datasets/rishab260/uta-reallife-drowsiness-dataset/Fold4_part2/Fold4_part2/47/5.mp4
47
Processing video: /kaggle/input/datasets/rishab260/uta-reallife-drowsiness-dataset/Fold4_part2/Fold4_part2/47/5.mp4
Done: 5.mp4 | processed=1802, saved=1802, failed=0
Extracted frame features: 1802
✅ Used baseline for subject: 47
Created windows: 1788

Average class probabilities:

           class  average_probability
2  Low Vigilance             0.976773
0          Alert             0.011714
1         Drowsy             0.011513

Window prediction counts:
Low Vigilance: 1787
Alert: 1

========================================
✅ Final Video Prediction: Low Vigilance
========================================

In [38]:
display(prediction_windows.head())
prediction_windows["prediction"].value_counts()
prediction_windows.to_csv("/kaggle/working/test_video_predictions.csv", index=False)

print("✅ Saved predictions at: /kaggle/working/test_video_predictions.csv")

,EAR_mean,EAR_std,EAR_min,MAR_mean,MAR_max,pitch_mean,yaw_mean,EAR_dev_mean,MAR_dev_mean,prediction
0,0.309336,0.023248,0.28351,0.007876,0.012619,231.100372,387.042458,-0.027779,0.002260,Low Vigilance
1,0.312010,0.023875,0.28351,0.008456,0.012619,229.385464,383.802663,-0.025105,0.002839,Low Vigilance
2,0.313832,0.022875,0.28351,0.008511,0.012619,228.005915,381.044657,-0.023283,0.002894,Low Vigilance
3,0.315134,0.021684,0.28351,0.009048,0.012619,226.347432,378.087236,-0.021981,0.003432,Low Vigilance
4,0.316458,0.021064,0.28351,0.009089,0.012619,224.860678,376.021265,-0.020657,0.003472,Low Vigilance

✅ Saved predictions at: /kaggle/working/test_video_predictions.csv

In [ ]:
df = pd.read_csv("/kaggle/working/metadata_clean.csv")

test_index = 0

test_video_path = df.iloc[test_index]["path"]
test_subject = df.iloc[test_index]["subject"]
true_label = df.iloc[test_index]["label"]

print("Video:", test_video_path)
print("Subject:", test_subject)
print("True label:", true_label)

final_prediction, prediction_windows = predict_video(
    video_path=test_video_path,
    subject=test_subject,
    sample_rate=10,
    window_size=15
)

print("True label:", true_label)
print("Predicted label:", final_prediction)

In [ ]:
import cv2
import numpy as np
import pandas as pd
import joblib
import mediapipe as mp
from collections import deque, Counter

from mediapipe.tasks import python
from mediapipe.tasks.python import vision


# =========================
# 1. LOAD SAVED MODEL FILES
# =========================

model = joblib.load("random_forest_model.pkl")
le = joblib.load("label_encoder.pkl")
feature_columns = joblib.load("feature_columns.pkl")

print("✅ Model loaded")
print("Classes:", le.classes_)
print("Feature columns:", feature_columns)


# =========================
# 2. LOAD MEDIAPIPE MODEL
# =========================

base_options = python.BaseOptions(
    model_asset_path="face_landmarker.task"
)

options = vision.FaceLandmarkerOptions(
    base_options=base_options,
    running_mode=vision.RunningMode.IMAGE,
    num_faces=1,
    output_face_blendshapes=False,
    output_facial_transformation_matrixes=False
)

detector = vision.FaceLandmarker.create_from_options(options)

print("✅ FaceLandmarker ready")


# =========================
# 3. LANDMARK DEFINITIONS
# =========================

# Eye landmarks for EAR
LEFT_EYE = [33, 160, 158, 133, 153, 144]
RIGHT_EYE = [362, 385, 387, 263, 373, 380]

# Mouth landmarks for MAR
MOUTH_TOP = 13
MOUTH_BOTTOM = 14
MOUTH_LEFT = 78
MOUTH_RIGHT = 308

# Approximate head pose landmarks
NOSE = 1
CHIN = 152
LEFT_FACE = 234
RIGHT_FACE = 454


# =========================
# 4. FEATURE FUNCTIONS
# =========================

def compute_EAR(landmarks, eye):
    """
    EAR = Eye Aspect Ratio.
    Smaller EAR means eyes are more closed.
    """
    p1, p2, p3, p4, p5, p6 = [np.array(landmarks[i][:2]) for i in eye]

    vertical1 = np.linalg.norm(p2 - p6)
    vertical2 = np.linalg.norm(p3 - p5)
    horizontal = np.linalg.norm(p1 - p4)

    return (vertical1 + vertical2) / (2.0 * horizontal + 1e-6)


def compute_MAR(landmarks):
    """
    MAR = Mouth Aspect Ratio.
    Larger MAR can indicate open mouth/yawning.
    """
    top = np.array(landmarks[MOUTH_TOP][:2])
    bottom = np.array(landmarks[MOUTH_BOTTOM][:2])
    left = np.array(landmarks[MOUTH_LEFT][:2])
    right = np.array(landmarks[MOUTH_RIGHT][:2])

    vertical = np.linalg.norm(top - bottom)
    horizontal = np.linalg.norm(left - right)

    return vertical / (horizontal + 1e-6)


def compute_head_pose_approx(landmarks):
    """
    Approximate head pose features.
    Same as your training code.
    """
    nose = np.array(landmarks[NOSE][:2])
    chin = np.array(landmarks[CHIN][:2])
    left = np.array(landmarks[LEFT_FACE][:2])
    right = np.array(landmarks[RIGHT_FACE][:2])

    pitch = np.linalg.norm(nose - chin)
    yaw = np.linalg.norm(left - right)

    return pitch, yaw


def get_face_landmarks_from_frame(frame_bgr):
    """
    Input: OpenCV BGR frame
    Output: list of pixel landmarks [(x, y, z), ...] or None
    """

    rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)

    mp_image = mp.Image(
        image_format=mp.ImageFormat.SRGB,
        data=rgb
    )

    result = detector.detect(mp_image)

    if not result.face_landmarks:
        return None

    h, w, _ = frame_bgr.shape

    landmarks_px = []

    for lm in result.face_landmarks[0]:
        x = int(lm.x * w)
        y = int(lm.y * h)
        z = lm.z
        landmarks_px.append((x, y, z))

    return landmarks_px


def extract_features_from_frame(frame):
    """
    Extract EAR, MAR, pitch, yaw from one webcam frame.
    """

    landmarks = get_face_landmarks_from_frame(frame)

    if landmarks is None:
        return None

    try:
        left_ear = compute_EAR(landmarks, LEFT_EYE)
        right_ear = compute_EAR(landmarks, RIGHT_EYE)
        EAR = (left_ear + right_ear) / 2.0

        MAR = compute_MAR(landmarks)
        pitch, yaw = compute_head_pose_approx(landmarks)

        return {
            "EAR": EAR,
            "MAR": MAR,
            "pitch": pitch,
            "yaw": yaw
        }

    except Exception as e:
        print("Feature extraction error:", e)
        return None


# =========================
# 5. WINDOW FEATURE FUNCTION
# =========================

def create_window_features(buffer, baseline_EAR, baseline_MAR):
    """
    Convert last 15 frame-level features into one row for model prediction.
    This must match your training features.
    """

    df = pd.DataFrame(list(buffer))

    df["EAR_dev"] = df["EAR"] - baseline_EAR
    df["MAR_dev"] = df["MAR"] - baseline_MAR

    row = {
        "EAR_mean": df["EAR"].mean(),
        "EAR_std": df["EAR"].std(),
        "EAR_min": df["EAR"].min(),
        "MAR_mean": df["MAR"].mean(),
        "MAR_max": df["MAR"].max(),
        "pitch_mean": df["pitch"].mean(),
        "yaw_mean": df["yaw"].mean(),
        "EAR_dev_mean": df["EAR_dev"].mean(),
        "MAR_dev_mean": df["MAR_dev"].mean()
    }

    X = pd.DataFrame([row])

    # Ensure same column order as training
    X = X[feature_columns]

    return X


# =========================
# 6. MAIN REAL-TIME FUNCTION
# =========================

def run_realtime_prediction(
    webcam_index=0,
    window_size=15,
    calibration_frames=60,
    sample_every_n_frames=3,
    smoothing_window=10
):
    """
    Real-time prediction from webcam.

    calibration_frames:
        Number of valid face frames used to calculate EAR/MAR baseline.

    sample_every_n_frames:
        Process every Nth webcam frame.
        If webcam is slow, use 2 or 3.
        If CPU is weak, use 5.

    smoothing_window:
        Majority voting over last N predictions.
    """

    cap = cv2.VideoCapture(webcam_index)

    if not cap.isOpened():
        print("❌ Could not open webcam")
        return

    print("✅ Webcam opened")
    print("Calibration started...")
    print("Please look normal/alert at the camera.")

    frame_count = 0
    calibration_data = []

    # =========================
    # CALIBRATION PHASE
    # =========================

    while len(calibration_data) < calibration_frames:
        ret, frame = cap.read()

        if not ret:
            print("❌ Failed to read webcam frame")
            break

        frame = cv2.flip(frame, 1)
        frame_count += 1

        display_frame = frame.copy()

        cv2.putText(
            display_frame,
            f"Calibration: {len(calibration_data)}/{calibration_frames}",
            (30, 50),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (0, 255, 255),
            2
        )

        cv2.putText(
            display_frame,
            "Stay ALERT and look at camera",
            (30, 90),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 255, 255),
            2
        )

        if frame_count % sample_every_n_frames == 0:
            features = extract_features_from_frame(frame)

            if features is not None:
                calibration_data.append(features)

        cv2.imshow("Real-Time Drowsiness Detection", display_frame)

        if cv2.waitKey(1) & 0xFF == ord("q"):
            cap.release()
            cv2.destroyAllWindows()
            return

    if len(calibration_data) == 0:
        print("❌ Calibration failed. No face detected.")
        cap.release()
        cv2.destroyAllWindows()
        return

    calibration_df = pd.DataFrame(calibration_data)

    baseline_EAR = calibration_df["EAR"].mean()
    baseline_MAR = calibration_df["MAR"].mean()

    print("✅ Calibration completed")
    print("Baseline EAR:", baseline_EAR)
    print("Baseline MAR:", baseline_MAR)

    # =========================
    # PREDICTION PHASE
    # =========================

    feature_buffer = deque(maxlen=window_size)
    prediction_buffer = deque(maxlen=smoothing_window)

    current_prediction = "Collecting frames..."
    current_confidence = 0.0

    print("✅ Real-time prediction started")
    print("Press 'q' to quit")

    while True:
        ret, frame = cap.read()

        if not ret:
            print("❌ Failed to read frame")
            break

        frame = cv2.flip(frame, 1)
        frame_count += 1

        display_frame = frame.copy()

        if frame_count % sample_every_n_frames == 0:
            features = extract_features_from_frame(frame)

            if features is not None:
                feature_buffer.append(features)

                if len(feature_buffer) == window_size:
                    X_live = create_window_features(
                        feature_buffer,
                        baseline_EAR,
                        baseline_MAR
                    )

                    pred_encoded = model.predict(X_live)[0]
                    pred_label = le.inverse_transform([pred_encoded])[0]

                    prediction_buffer.append(pred_label)

                    # Majority vote smoothing
                    current_prediction = Counter(prediction_buffer).most_common(1)[0][0]

                    if hasattr(model, "predict_proba"):
                        probs = model.predict_proba(X_live)[0]
                        current_confidence = np.max(probs) * 100

        # Choose color based on prediction
        if current_prediction == "Alert":
            color = (0, 255, 0)
        elif current_prediction == "Low Vigilance":
            color = (0, 255, 255)
        elif current_prediction == "Drowsy":
            color = (0, 0, 255)
        else:
            color = (255, 255, 255)

        # Display prediction
        cv2.putText(
            display_frame,
            f"Prediction: {current_prediction}",
            (30, 50),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            color,
            2
        )

        cv2.putText(
            display_frame,
            f"Confidence: {current_confidence:.2f}%",
            (30, 90),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            color,
            2
        )

        cv2.putText(
            display_frame,
            f"Buffer: {len(feature_buffer)}/{window_size}",
            (30, 130),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (255, 255, 255),
            2
        )

        cv2.putText(
            display_frame,
            "Press q to quit",
            (30, display_frame.shape[0] - 30),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (255, 255, 255),
            2
        )

        cv2.imshow("Real-Time Drowsiness Detection", display_frame)

        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

    cap.release()
    cv2.destroyAllWindows()
    print("✅ Webcam closed")


# =========================
# 7. RUN
# =========================

if __name__ == "__main__":
    run_realtime_prediction(
        webcam_index=0,
        window_size=15,
        calibration_frames=60,
        sample_every_n_frames=3,
        smoothing_window=10
    )